# .github/workflows/dependency-check.yml
name: OWASP Dependency Check

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run OWASP Dependency Check
      run: |
        mvn dependency-check:check -Dformat=HTML -DoutputDirectory=target

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html
