# .github/workflows/docker-deploy.yml
name: Docker Build and Push

on:
  workflow_call:

jobs:
  docker:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Docker login
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.DOCKERHUB_REGISTRYURL }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Verify Docker login
      run: |
        docker info  # Verify that the login was successful

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_REGISTRYURL }}/${{ secrets.DOCKERHUB_APPNAME }}:${{ github.sha }}-${{ github.run_number }}"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
