# .github/workflows/docker-deploy.yml
name: Docker Build and Push

on:
  workflow_call:

jobs:
  docker:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Docker login
      uses: azure/docker-login@v2
      with:
        login-server: gitpracacr.azurecr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Verify Docker login
      run: |
        docker info  # Verify that the login was successful

    - run: |
        docker build . -t gitpracacr.azurecr.io/petclinic:${{ github.sha }} 
        docker push gitpracacr.azurecr.io/petclinic:${{ github.sha }} 
