name: Triggered by Port

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project (from Port)'
        required: true

jobs:
  trigger-from-port:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Project Name: ${{ github.event.inputs.project_name }}"

      # This step updates the run status back to Port
      - name: Update Run Status to Port
        env:
          PORT_API_TOKEN: ${{ secrets.PORT_API_TOKEN }} # Set the Port API token in GitHub secrets
        run: |
          completedAt=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

          # Send a PATCH request to Port API to update the run status
          curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $PORT_API_TOKEN" \
            -d "{
              \"status\": \"SUCCESS\",
              \"message\": {
                \"run_status\": \"Completed at $completedAt\"
              }
            }" \
            "https://api.getport.io/v1/actions/runs/$PORT_RUN_ID"
