# .github/workflows/ci-cd-pipeline.yml
name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run setup-java workflow
      run: |
        echo "Running setup-java workflow from another workflow"

    - name: Run Secrets Scan
      uses: ./.github/workflows/secrets-scan.yml

    - name: SonarQube Analysis
      uses: ./.github/workflows/sonar-scanner.yml

    - name: Run Dependency Check
      uses: ./.github/workflows/dependency-check.yml

    - name: Run Docker Build and Push
      uses: ./.github/workflows/docker-deploy.yml

    - name: Run Trivy Security Scan
      uses: ./.github/workflows/trivy-scan.yml
