name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Java and Maven Workflow Trigger
    - name: Trigger setup-java workflow
      run: |
        echo "Triggering setup-java workflow..."

    # SonarQube Analysis Workflow Trigger
    - name: Trigger sonar-scanner workflow
      run: |
        echo "Triggering SonarQube Analysis..."

    # Dependency Check Workflow Trigger
    - name: Trigger dependency-check workflow
      run: |
        echo "Triggering dependency check workflow..."

    # Docker Build and Push Workflow Trigger
    - name: Trigger Docker build and push workflow
      run: |
        echo "Triggering Docker build and push workflow..."

    # Trivy Security Scan Workflow Trigger
    - name: Trigger Trivy scan workflow
      run: |
        echo "Triggering Trivy security scan workflow..."

