name: Triggered by Port

on:
  repository_dispatch:
    types: [port_trigger]

jobs:
  trigger-from-port:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Project Name: ${{ github.event.client_payload.project_name }}"
          echo "Run ID: ${{ github.event.client_payload.run_id }}"

      - name: Update Run Status to Port
        env:
          PORT_API_TOKEN: ${{ secrets.PORT_API_TOKEN }}
          PORT_RUN_ID: ${{ github.event.client_payload.run_id }}
        run: |
          completedAt=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

          curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $PORT_API_TOKEN" \
            -d "{
              \"status\": \"SUCCESS\",
              \"message\": {
                \"run_status\": \"Completed at $completedAt\"
              }
            }" \
            "https://api.getport.io/v1/actions/runs/$PORT_RUN_ID"
