# .github/workflows/secrets-scan.yml
name: Detect Secrets Scan

on:
  workflow_run:
    workflows: ["CI-CD Pipeline"]   # This references the main pipeline workflow
    types:
      - completed

jobs:
  secrets-scan:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install detect-secrets inside working directory
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install detect-secrets
        detect-secrets --version

    - name: Run detect-secrets scan to check for secrets
      run: |
        source venv/bin/activate
        rm -f .secrets.baseline
        detect-secrets scan --all-files > .secrets.baseline
        detect-secrets scan --all-files --exclude-files 'venv/*' > .secrets.baseline
        if jq '.results | length > 0' .secrets.baseline; then
        echo "Secrets found in the code:"
        jq '.results | to_entries[] | .value[] | "\(.filename): Line \(.line_number) - \(.type)"' .secrets.baseline
        else
        echo "No secrets detected, pipeline passes!"
        fi
