# .github/workflows/setup-java.yml
name: Set up Java and Maven

on:
  workflow_run:
    workflows: ["CI-CD Pipeline"]   # This references the main pipeline workflow
    types:
      - completed

jobs:
  setup:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 11
        java-distribution: temurin
        maven-version: 3.8.1

    - name: Build and package application
      run: mvn clean install
