# .github/workflows/trivy-scan.yml
name: Trivy Security Scan

on:
  workflow_call:

jobs:
  trivy-scan:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Run Trivy security scan
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_REGISTRYURL }}/${{ secrets.DOCKERHUB_APPNAME }}:${{ github.sha }}-${{ github.run_number }}"
        docker pull $IMAGE_NAME
        trivy image --exit-code 0 --severity HIGH,CRITICAL --no-progress $IMAGE_NAME
        #make it 1 to make sure the pipeline fails
