# .github/workflows/trivy-scan.yml
name: Trivy Security Scan

on:
  workflow_run:
    workflows: ["CI-CD Pipeline"]   # This references the main pipeline workflow
    types:
      - completed

jobs:
  trivy-scan:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run Trivy security scan
      run: |
        docker pull ${{ secrets.DOCKERHUB_REGISTRYURL }}/${{ secrets.DOCKERHUB_APPNAME }}:${{ github.run_number }}
        trivy image --exit-code 0 --severity HIGH,CRITICAL --no-progress ${{ secrets.DOCKERHUB_REGISTRYURL }}/${{ secrets.DOCKERHUB_APPNAME }}:${{ github.run_number }}
        #make it 1 to make sure the pipeline fails
